### ISSUE TITLE
How to set up name resolution for pods?

### ISSUE THREAD

**Issue by WolfangAukang** [containers/dnsname#40]
This is regarding #11 and https://github.com/containers/podman/pull/5657.

Would it be possible to document how to associate a hostname to a pod and perform connections between two different pods by hostname?

The idea is that I want to have a pod with a database running and another pod with any application able to connect to that pod. I have been performing the following as superuser:

```
podman network create foobar # It contains the dnsname plugin
podman pod create --name pod_db --network foobar --hostname db -p "3306"
podman run -d --pod pod_db --name mariadb -e MYSQL_RANDOM_ROOT_PASSWORD=1 mariadb:10.4
podman pod create --name pod_front --network foobar --hostname frontend
podman run -it --pod pod_front busybox sh
#### On busybox
/ # telnet db 3306
telnet: bad address 'db'
/ #
```
Is that possible to be done?

**Comment by baude** [comment]
As of now, dnsname only uses the name of the pod for name resolution.  the value of --hostname is ignored for dnsname.  I think it is a very interesting feature though and will give it some though.  Would it work for you to use the name of the pod?

**Comment by WolfangAukang** [comment]
Thanks for the info @baude, that works for me :).

The main plan was to deploy stuff on separate pods and test connections between them. Right now, changing the hostname to pod_db while running the telnet command made it work as expected, so I think I can handle my use case normally from here.

**Comment by cfelder** [comment]
Sorry for reopening this conversation but I stumbled across this on my fedora 33 system

```
Version:      2.1.1
API Version:  2.0.0
Go Version:   go1.15.2
Built:        Mon Oct  5 01:25:24 2020
OS/Arch:      linux/amd64
```

> As of now, dnsname only uses the name of the pod for name resolution. the value of --hostname is ignored for dnsname.

Would it be possible to provide some feedback to the user when using ``--hostname`` with ``dnsname`` plugin? I expected to have the value of ``--hostname`` in ``addnhosts`` rather than the argument provided by ``--name``.
I can life with using what is in ``--name`` but it is misleading that ``--hostname`` is silently ignored.

On CentOS 8 unfortunately the name of the infra container is passed down to cni but I hope this situation will improve when releasing 8.3
```
Version:            1.6.4
RemoteAPI Version:  1
Go Version:         go1.13.4
OS/Arch:            linux/amd64
```
